### ISSUE TITLE
Is it possible to boost more than 1 account?

### ISSUE THREAD

**Issue by 7eb0xdd** [ZixeSea/SteamIdler#1]
^ title

**Comment by ZixeSea** [comment]
That's an interesting question.

Currently, it only supports just 1 but I could try to make it work with multiple.
I can see the benefits fo adding multiple accounts.

**Comment by zoomingbye** [comment]
Any update? Really invested in adding multiple accounts to boost from one instance.

**Comment by ZixeSea** [comment]
I was thinking of adding that with the rewrite I did and the new code also should make it easier to add but I'm busy. I own a big discord bot that I'm currently working on (slash command related). I maybe add it after I'm done with the bot, so it's not off the table.

**Comment by zoomingbye** [comment]
I see, will be patiently waiting, best of luck !

**Comment by ZixeSea** [comment]
### Started working on multi account support, first working test
![image](https://github.com/ZixeSea/SteamIdler/assets/14878416/6b0b255a-82b4-4c0c-a92e-7116a1759f69)

**Comment by ZixeSea** [comment]
Multi account support added in v2, it now live
