### ISSUE TITLE
[Feature] Allow static and dynamic idler to work together

### ISSUE THREAD

**Issue by RedSparr0w** [ZixeSea/SteamIdler#10]
Allow the dynamic and static idlers to work together

My thoughts on how this would work:

Static idler prioritized over dynamic idler
Any spare spaces remaining will be filled by the dynamic idler

**Comment by ZixeSea** [comment]
When I read the title I got the same idea as you mentioned here. And it sounds good

**Comment by ZixeSea** [comment]
Would you be able to test this PR @RedSparr0w
